---
- name: Load common configuration
  import_playbook: ../static-assignments/common.yml

- name: Load environment variables
  import_playbook: ../dynamic-assignments/env-vars.yml

- name: Include UAT specific playbook
  import_playbook: ../static-assignments/uat-webservers.yml
  when: env == "uat"

- name: Include Load balancer playbook
  import_playbook: ../static-assignments/loadbalancers.yml
